### ISSUE TITLE
Too many values to unpack error

### ISSUE THREAD

**Issue by partofthething** [EronHennessey/sphinx-mobi-builder#3]
Running this with a `2to3` converted version on the most recent sphinx gives the following traceback:
```
# Sphinx version: 1.8.3
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14⋅
# Jinja2 version: 2.10
# Last messages:
#   writing output... [ 90%] glossary                                                                                                                                                                              
#⋅⋅⋅
#   writing output... [100%] index
#⋅⋅⋅
#⋅⋅⋅
#⋅⋅⋅
#   generating indices...
#⋅⋅⋅
#   genindex
#⋅⋅⋅
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.3) from /home/nick/.local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /home/nick/.local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.imgmath (1.8.3) from /home/nick/.local/lib/python3.6/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.graphviz (1.8.3) from /home/nick/.local/lib/python3.6/site-packages/sphinx/ext/graphviz.py
#   sphinxcontrib.tikz (0.4.6) from /home/nick/.local/lib/python3.6/site-packages/sphinxcontrib/tikz.py
#   sphinx.builders.mobi (unknown version) from /home/nick/.local/lib/python3.6/site-packages/sphinx/builders/mobi.py
Traceback (most recent call last):
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 415, in build
    self.finish()
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/html.py", line 749, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/util/parallel.py", line 51, in add_task
    res = task_func()
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/html.py", line 766, in gen_indices
    self.write_genindex()
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/html.py", line 828, in write_genindex
    self.handle_page('genindex', genindexcontext, 'genindex.html')
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/mobi.py", line 336, in handle_page
    self.fix_genindex(addctx['genindexentries'])
  File "/home/nick/.local/lib/python3.6/site-packages/sphinx/builders/mobi.py", line 315, in fix_genindex
    for entryname, (links, subitems) in columns:
ValueError: too many values to unpack (expected 2)
```

**Comment by EronHennessey** [comment]
Hi there, thanks for this report.  I'm going to look at this error and the other issue (Python3 support) at once...

**Comment by EronHennessey** [comment]
Hey, check [my response](https://github.com/EronHennessey/sphinx-mobi-builder/issues/2#issuecomment-470363064) to the [previous issue](https://github.com/EronHennessey/sphinx-mobi-builder/issues/2)... ;)

This is actually better suited as a comment on that issue, anyway, since it's about the Python3 incompatibility of this extension. Closing this in favor of that one.
